#ddev-generated
services:
  typesense:
    container_name: ddev-${DDEV_SITENAME}-typesense
    image: typesense/typesense:26.0
    command: '--data-dir /data --api-key=ddev --enable-cors'
    networks: [ default, ddev_default ]
    restart: on-failure
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    expose:
      - 8108
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=8108:8108
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "typesense:/data"

  typesense-dashboard:
    container_name: ddev-${DDEV_SITENAME}-typesense-dashboard
    image: ghcr.io/bfritscher/typesense-dashboard:latest
    restart: on-failure
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    ports:
      - "8109:80"
    environment:
      - VIRTUAL_HOST=typesense.$DDEV_HOSTNAME
    external_links:
      - "ddev-router:${DDEV_HOSTNAME}"
    volumes:
      - "./typesense/dashboard-config.json:/srv/config.json"

volumes:
  typesense:

